//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course()
        {
            this.registStudent2Course = new HashSet<registStudent2Course>();
        }
    
        public int Id { get; set; }
        public string day { get; set; }
        public string st_hour { get; set; }
        public string end_hour { get; set; }
        public string classroom { get; set; }
        public string Moad1 { get; set; }
        public string Moad2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registStudent2Course> registStudent2Course { get; set; }
    }
}
